"""Observability surface: OTel bootstrap + tracing/metrics helpers.

Public entry points:
- ``init_otel()`` — call once at process start, before FastAPI app construction.
- ``tracer``, ``meter`` — module-level instruments; safe no-ops when OTel is unconfigured.
- ``chat_turn_observed`` — async context manager that owns the turn span + counter + duration + in-flight gauge.
- ``traced_body`` — wraps a StreamingResponse body generator so child spans stay parented to the turn.
- ``create_task_with_context`` — ``asyncio.create_task`` wrapper that snapshots contextvars (including OTel context) so spans in the spawned coroutine nest under the launching trace.

The full surface stays no-op when ``OTEL_EXPORTER_OTLP_ENDPOINT`` is unset — instrumentation
call sites are always safe to leave in place.
"""

from .otel import init_otel, init_otel_runtime, shutdown_otel_runtime
from .tracing import (
    attached,
    chat_turn_observed,
    create_task_with_context,
    emit_subagent_launch,
    hash_id,
    observe_background_chat_turn,
    observe_chat_stream,
    observe_replay_stream,
    safe_add,
    safe_aspan,
    safe_record,
    safe_span,
    traced_body,
    tracer,
)
from .metrics import (
    automation_executions,
    chat_turn_duration_ms,
    chat_turn_phase_duration_ms,
    chat_turns_counter,
    chat_turns_in_flight,
    hot_path_first_chunk_duration_ms,
    credits,
    llm_tokens,
    memo_uploaded,
    meter,
    replay_bytes_distribution,
    replay_bytes_emitted,
    replay_duration_ms,
    replay_events_distribution,
    replay_events_emitted,
    replay_size_bucket,
    sandbox_asset_sync_phase_duration_ms,
    sandbox_asset_sync_total_ms,
    sandbox_execute_duration_ms,
    sandbox_user_data_upload_duration_ms,
    session_acquire_phase_duration_ms,
    session_acquire_total_ms,
    session_path_counter,
    sse_reconnects,
    subagent_launches,
    workspace_cold_start_duration_ms,
    workspace_created,
    workspace_fs_bytes,
    ws_connection_duration_seconds,
    ws_connections_active,
    ws_disconnects,
    ws_messages_sent,
)

__all__ = [
    "init_otel",
    "init_otel_runtime",
    "shutdown_otel_runtime",
    "tracer",
    "meter",
    "hash_id",
    "safe_record",
    "safe_add",
    "attached",
    "safe_span",
    "safe_aspan",
    "chat_turn_observed",
    "create_task_with_context",
    "emit_subagent_launch",
    "observe_background_chat_turn",
    "observe_chat_stream",
    "observe_replay_stream",
    "traced_body",
    "chat_turns_counter",
    "chat_turn_duration_ms",
    "chat_turns_in_flight",
    "llm_tokens",
    "credits",
    "workspace_created",
    "workspace_cold_start_duration_ms",
    "workspace_fs_bytes",
    "sandbox_execute_duration_ms",
    "subagent_launches",
    "memo_uploaded",
    "automation_executions",
    "sse_reconnects",
    "ws_connections_active",
    "ws_connection_duration_seconds",
    "ws_messages_sent",
    "ws_disconnects",
    "hot_path_first_chunk_duration_ms",
    "chat_turn_phase_duration_ms",
    "replay_bytes_distribution",
    "replay_bytes_emitted",
    "replay_duration_ms",
    "replay_events_distribution",
    "replay_events_emitted",
    "replay_size_bucket",
    "session_acquire_phase_duration_ms",
    "session_acquire_total_ms",
    "session_path_counter",
    "sandbox_asset_sync_phase_duration_ms",
    "sandbox_asset_sync_total_ms",
    "sandbox_user_data_upload_duration_ms",
]
